name: Deploy ERP Frontend To VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: akhileshrawat7/rolaface-erp-frontend:latest
          build-args: |
            VITE_API_BASE_URL=https://erp.izyanehub.com/api

            VITE_ZRA_CLIENT_API=https://erp.izyanehub.com/api/method/erpnext.zra_client
            VITE_INVOICE_API_URL=https://erp.izyanehub.com/api/method/erpnext.zra_client.sales.api
            VITE_ITEM_API_URL=https://erp.izyanehub.com/api/method/erpnext.zra_client.item.item
            VITE_PROFORMA_API_URL=https://erp.izyanehub.com/api/method/erpnext.proforma.api
            VITE_QUOTATION_API_URL=https://erp.izyanehub.com/api/method/erpnext.quotation.api
            VITE_DEBIT_NOTE_API_URL=https://erp.izyanehub.com/api/method/erpnext.zra_client.sales.api
            VITE_CREDIT_NOTE_API_URL=https://erp.izyanehub.com/api/method/erpnext.zra_client.sales.api
            VITE_CUSTOMER_API_URL=https://erp.izyanehub.com/api/method/erpnext.zra_client.customer.customer
            VITE_CUSTOMER_STATEMENT_API_URL=https://erp.izyanehub.com/api/method/erpnext.zra_client.customer.statement.api
            VITE_SUPPLIER_API_URL=https://erp.izyanehub.com/api/method/erpnext.supplier.api
            VITE_PO_API_URL=https://erp.izyanehub.com/api/method/erpnext.zra_client.purchase.order

            VITE_COMPANY_API_URL=https://erp.izyanehub.com/api/method/erpnext.company-setup.setup

            VITE_HRMS_API_URL=https://erp.izyanehub.com/api/method/hrms.napsa_client
            VITE_NAPSA_MEMBER_API_URL=https://erp.izyanehub.com/api/method/hrms.napsa_client

            VITE_ZRA_CODES_API_URL=https://zra-codes.izyanehub.com/api
            VITE_CLASS_LIST_API_URL=https://zra-codes.izyanehub.com/api
            VITE_COUNTRY_LIST_API_URL=https://zra-codes.izyanehub.com/api
            VITE_PACKAGING_UNIT_CODES_API_URL=https://zra-codes.izyanehub.com/api
            VITE_UNIT_OF_MEASURE_API_URL=https://zra-codes.izyanehub.com/api

            VITE_API_AUTH_TOKEN=token 1e329714a6374c6:812f742ecb4aa0d
            VITE_COMPANY_ID=COMP-00003

      - name: Copy deploy script to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: ".github/workflows/deploy.sh"
          target: "/root/deploy-scripts/erp-frontend"
          strip_components: 2

      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            SCRIPT_PATH="/root/deploy-scripts/erp-frontend/deploy.sh"
            chmod +x $SCRIPT_PATH
            $SCRIPT_PATH
