name: Deploy ERP Frontend To VPS

on:
  push:
    branches: ["rolaface"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Trigger Vercel Hook
      #   run: |
      #     curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_STAGING }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: akhileshrawat7/rolaface-erp-frontend:staging
          build-args: |
            VITE_API_BASE_URL=${{ secrets.ERP_API_BASE_URL }}
            VITE_ZRA_CODES_BASE_URL=${{ secrets.ERP_ZRA_CODES_BASE_URL }}
            VITE_API_AUTH_TOKEN=${{ secrets.ERP_AUTH_TOKEN }}
            VITE_COMPANY_ID=${{ secrets.ERP_COMPANY_ID }}
            VITE_NAPSA_BASE_URL=${{ secrets.ERP_NAPSA_BASE_URL }}

      - name: Copy deploy script to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: ".github/workflows/deploy-staging.sh"
          target: "/root/deploy-scripts/erp-frontend"
          strip_components: 2

      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            SCRIPT_PATH="/root/deploy-scripts/erp-frontend/deploy-staging.sh"
            chmod +x $SCRIPT_PATH
            $SCRIPT_PATH
